### ISSUE TITLE
Eigen thema activeren op jouw online wp-site

### ISSUE THREAD

**Issue by Theo-denBlanken** [GijsHuitenga/WP-thema-maken#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/GijsHuitenga/WP-thema-maken/blob/master/

Feedback: zodat te zien is hoe het uitpakt[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by GijsHuitenga** [comment]
Mijn custom thema is al actief
